version: '3'
services:

  user-service:
    build:
      context: ./backend_mongodb/user  # Updated build context path
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - mynetwork
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    
  post-service:
    build:
      context: ./backend_mongodb/post  # Updated build context path
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - mynetwork
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
      - minio

  notification-service:
    build:
      context: ./backend_mongodb/notification  # Updated build context path
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - mynetwork
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
  

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    volumes:
      - minio_data:/data
    command: minio server /data


  mongodb:
    image: mongo:4.4.24
    networks:
      - mynetwork
    ports:
      - "27017:27017"

  nginx:
    build:
      context: ./frontend
    image: nginx:latest
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - post-service
      - notification-service

volumes:
  minio_data:

networks:
  mynetwork: